Vidly/Controllers/CustomerController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidlyMovies.Models;
using VidlyMovies.ViewModels;

namespace VidlyMovies.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;

        public CustomerController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            var modelName = User.IsInRole(VidlyRoles.CanManageRole) ? "List":"ReadOnly";
            return View(modelName, _context.Customers.Include(c => c.MembershipType).OrderBy(c => c.ID));
        }

        public ActionResult Details(int? id)
        {
            Customer selectedCustomer = null;
            if (id.HasValue)
            {
                var customerID = id.GetValueOrDefault(0);
                selectedCustomer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.ID == customerID);
                if (selectedCustomer != null)
                {
                    ViewBag.ContainData = "1";
                    return View(selectedCustomer);
                }
                else
                {
                    ViewBag.ContainData = "0";
                    ViewBag.Description = "Customer details for Customer ID " + customerID + " not found.";
                    return View();
                }
            }
            else
            {
                ViewBag.ContainData = "2";
                ViewBag.Description = "Please select any customer to view details.";
                return View();
            }
        }

        [Authorize(Roles = VidlyRoles.CanManageRole)]
        public ActionResult New()
        {
            var newCustomerFormViewModel = new CustomerFormViewModel()
            {
                Customer = new Customer(),
                MembershipTypes = _context.MembershipTypes.ToList()
            };
            ViewBag.New = true;
            return View("CustomerForm",newCustomerFormViewModel);
        }

        [Authorize(Roles = VidlyRoles.CanManageRole)]
        public ActionResult Edit(int? id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.ID == id);
            var userName = User.Identity.GetUserName();
            if (customer == null)
                return HttpNotFound();


            var newCustomerFormViewModel = new CustomerFormViewModel()
            {
                Customer = customer,
                MembershipTypes = _context.MembershipTypes.ToList()
            };
            ViewBag.New = false;
            return View("CustomerForm", newCustomerFormViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = VidlyRoles.CanManageRole)]
        public ActionResult Save(Customer customer)
        {
            ViewBag.New = (customer.ID == 0);
            if (!ModelState.IsValid)
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer,
                    MembershipTypes = _context.MembershipTypes.ToList()
                };

                return View("CustomerForm", viewModel);
            }

            if (customer.ID == 0)
            {
                ViewBag.Description = "New Customer Details Saved Successfully For ";
                _context.Customers.Add(customer);
            }
            else
            {
                var customerFromDB = _context.Customers.SingleOrDefault(c => c.ID == customer.ID);
                customerFromDB.Name = customer.Name;
                customerFromDB.MembershipTypeID = customer.MembershipTypeID;
                customerFromDB.BirthDate = customer.BirthDate;
                customerFromDB.IsSubscribedToNewsLetter = customer.IsSubscribedToNewsLetter;
                ViewBag.Description = "Customer Details Updated Successfully For ";
            }
            _context.SaveChanges();

            ViewBag.ContainData = "1";
            return View("UpdatedDetails",customer);
        }

        [Authorize(Roles = VidlyRoles.CanManageRole)]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                var customerID = id.GetValueOrDefault(0);
                var selectedCustomer = _context.Customers.Single(c => c.ID == customerID);
                if (selectedCustomer != null)
                {
                    ViewBag.ContainData = "2";
                    _context.Customers.Remove(selectedCustomer);
                    _context.SaveChanges();
                    ViewBag.Description = selectedCustomer.Name + " Customer deleted";
                    return View("UpdatedDetails");
                }
                else
                {
                    
                    ViewBag.ContainData = "2";
                    ViewBag.Description = "Customer details for Customer ID " + customerID + " not found.";
                    return View("UpdatedDetails");
                }
            }
            else
            {
                ViewBag.ContainData = "2";
                ViewBag.Description = "Please select any customer to delete.";
                return View("UpdatedDetails");
            }
        }

    }
}

Vidly/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VidlyMovies.Controllers
{
    public class RentalController : Controller
    {
        // GET: Rentals
        [Authorize]
        public ActionResult New()
        {
            return View();
        }

        [Authorize]
        public ActionResult Returns()
        {
            return View();
        }
    }
}

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly by Kishore</p>
        </footer>
    </div>

    @*
        Included below bundles to custom bundle vidlylib
            @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/vidlylib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("New Rental", "New", "Rental")</li>
                <li>@Html.ActionLink("Returns", "Returns", "Rental")</li>
                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>